springfoxdocumentation:
  swagger:
    v2:
      path: /api-docs
      
server:
  port: ${PETSTOREORDERSERVICE_SERVER_PORT:8080}

petstore:
  service:
    product:
      url: ${PETSTOREPRODUCTSERVICE_URL:http://localhost:8082}
    servicebus:
      connection_string: ${SERVICEBUS_CONNECTION_STRING}
      queue_name: ${SERVICEBUS_QUEUE_NAME}

spring:
  application:
    name: petstoreorderservice
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cosmos:
    account_endpoint: ${COSMOS_ACCOUNT_ENDPOINT}
    account_key: ${COSMOS_ACCOUNT_KEY}

management:
  endpoints:
    web:
      exposure:
        include: "*"       
  trace:
    http:
      enabled: true 
  endpoint:
    httptrace:
      enabled: true
